//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63135741.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BookTable
    {
        public string BookTableID { get; set; }
        public string NameCus { get; set; }
        public string PhoneCus { get; set; }
        public string QuantityPP { get; set; }
        public System.TimeSpan TimeBook { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DayBook { get; set; }
        public string Note { get; set; }
    }
}
