//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63135741.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public string FoodsID { get; set; }
        public string PicFood { get; set; }
        public string FoodsName { get; set; }
        public string Descrip { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string KindID { get; set; }
    
        public virtual KindOfMenu KindOfMenu { get; set; }
    }
}
