//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63135741.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Project_63135741Entities : DbContext
    {
        public Project_63135741Entities()
            : base("name=Project_63135741Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<KindOfMenu> KindOfMenus { get; set; }
        public virtual DbSet<BookTable> BookTables { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
    
        public virtual int Find_Menu(string menuName, string kindID)
        {
            var menuNameParameter = menuName != null ?
                new ObjectParameter("MenuName", menuName) :
                new ObjectParameter("MenuName", typeof(string));
    
            var kindIDParameter = kindID != null ?
                new ObjectParameter("KindID", kindID) :
                new ObjectParameter("KindID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Find_Menu", menuNameParameter, kindIDParameter);
        }
    }
}
